# pytest.ini
[pytest]
python_files = *_tests.py test_*.py   # Устанавливает правила для тестовых файлов
python_classes = Test*               # Устанавливает правила для имен классов
python_functions = test_*            # Устанавливает правила для имен функций
markers=
    users: Маркировка для тестов, связанных с пользователями
    regression: Маркировка для регрессионных тестов
    authentication: Маркировка для тестов с аутентификацией

# Если вы хотите временно запустить тесты только из определённых файлов или по шаблону в имени, можно использовать
;опцию -k. Она позволяет фильтровать тесты по имени файла, функции или класса.
;Примеры:
;python -m pytest -k "example"

;1. функции должны начинаться с test:
;(test_login_page_renders_correctly()
;test_user_can_register()
;test_product_addition_to_cart()

;2. классы должны начинаться с Test;
; class TestUserAuthentication:
;    def test_login(self):
;        assert 1 == 1

;Имена методов внутри класса также должны начинаться с test_, чтобы pytest мог обнаружить их как тесты.
;Классы не должны иметь конструктора (__init__()), так как pytest не может корректно создавать экземпляры таких классов.
;Pytest создает экземпляр класса для каждого теста, и наличие конструктора может нарушить этот процесс.